services:
  locadoradeautomoveis.webapi:
    image: ${DOCKER_REGISTRY-}locadoradeautomoveiswebapi
    build:
      context: .
      dockerfile: web-api/Dockerfile
    depends_on:
      mssqlserver:
        condition: service_healthy
    networks:
      - locadoradeautomoveis-net

  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: locadora-de-automoveis-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'timeout 1 bash -c \"</dev/tcp/localhost/1433\"'"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - locadoradeautomoveis-net

  redis:
    image: redis:8.2.1
    container_name: locadora-de-automoveis-redis
    command: >
      redis-server
      --appendonly yes
      --save 60 1000
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - locadoradeautomoveis-net

networks:
  locadoradeautomoveis-net:
    driver: bridge

volumes:
  locadoradeautomoveis-dbdata:
  locadoradeautomoveis-redisdata:
